name: Deploy API to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'API/**'
      - '.github/workflows/azure-webapp.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install API deps
        working-directory: API
        run: npm ci

      # If you build anything (tsc, etc.), do it here:
      # - name: Build API
      #   working-directory: API
      #   run: npm run build

      - name: Zip API app
        run: |
          cd API
          zip -r ../api-release.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: lockedin-backend-d7hze6awadd3fqbh
          package: api-release.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
